import React, {Component} from 'react';
import Swipeout from 'react-native-swipeout';
const Instructions = require('../../components/Instructions');
const AddSectionButton = require('../../components/AddSectionButton');
const Board = require('../../components/Board');
const styles = require('../../styles.js');

import {
	Text,
	View,
	Dimensions,
	ListView,
	TextInput,
} from 'react-native';

var maxBoardLength = 0; // Length of longest board
var isMounted; // Boolean variable indicating whether or not component has mounted yet
var endsArray; // Array that will hold lengths of all ends
var selectedProjectKey; // Key generated by Firebase corresponding to project currently under consideration
var selectedProjectTitle; // Title input by user corresponding to project currently under consideration
var ends; // Array of ends in ListView-friendly format

export default class Screen4 extends Component {
	static navigationOptions = {
    	title: 'Screen4',
		header: null
  	};

  	constructor(props) {
		super(props);
	    this.state = {
	    	dataSource: new ListView.DataSource({
	        	rowHasChanged: (row1, row2) => row1 !== row2,
	    	}),
	    	boardLength: 0,
	    };
	    maxEndLength = 0;
    	endsArray = this.props.endsArray;
    	selectedProjectKey = this.props.selectedProjectKey;
    	selectedProjectTitle = this.props.selectedProjectTitle;
    	ends = this.props.ends;
	}

	// COMPONENT LIFECYCLE METHODS

	componentDidMount() {
 		// Initialize event listener for database
    	this.listenForItems(this.props.itemsRef);
    }

    componentWillMount() {
    	isMounted = true;
    }

    componentWillUnmount() {
    	isMounted = false;
    }

    // DATA SAVING METHODS

	setEndsArray = (endsArrayReceived) => {
		this.props.setEndsArray(endsArrayReceived);
		endsArray = endsArrayReceived;
	}

	setMaxEndLength = (maxEndLengthReceived) => {
		this.props.setMaxEndLength(maxEndLengthReceived);
		maxEndLength = maxEndLengthReceived;
	}

	saveLength = (length) => {
		this.setState({
			endLength: length,
		});
	}

	saveData = () => {
		this.props.itemsRef.child(selectedProjectKey).child(selectedProjectTitle).child('ends').push(this.state.endLength);
	}

	// EVENT LISTENERS

    // Listen for and pull data from DB into dataSource
 	listenForItems(itemsRef) {
 		// Call callback function on data snapshot whenever values in database change
	    itemsRef.on('value', (snap) => {
	    	if (!isMounted)
	    		return;
	      	var items = []; // empty array in which we'll load all data
	      	this.setEndsArray([]);
  			snap.child(selectedProjectKey).child(selectedProjectTitle).child('ends').forEach((end) => {
  				// If current end is longer than max so far, update max so far
  				if (parseFloat(end.val()) > maxEndLength) {
  					this.setMaxEndLength(end.val());
  				}
  				if (end.key != 'default') { // If end is not the 'default' placeholder end
  					endsArray.push(parseFloat(end.val())); // save end in endsArray
	  				items.push({ // save end in items
	  					title: end.val(),
				        _key: end.key
	  				});
  				}
  			});
		    this.setState({
		        dataSource: this.state.dataSource.cloneWithRows(items) // save ends in dataSource
		    }, () => {
		    	this.props.setEnds(this.state.dataSource); // save ends in shared 'ends' variable
		    });
	    });
	}


	renderItem(item) {
		// Settings to determine behaviour when end is swiped
		const swipeSettings = {
			autoClose: true,
			onClose: (secId, rowId, direction) => {
				this.props.itemsRef.child(selectedProjectKey).child(selectedProjectTitle).child('ends').child(item._key).remove();
			}
		}
		// Define 'delete' button
		var swipeBtns = [{
			text: 'Delete',
			backgroundColor: 'red',
			underlayColor: 'rgba(0, 0, 0, 1, 0.6)',
		}];
		return (
    		<View>
    			<View style={{width: (item.title/parseFloat(maxEndLength))*(Dimensions.get('window').width-4), borderColor: 'black', borderBottomWidth: 1}}>
			    	<Swipeout {...swipeSettings} style={styles.board} right={swipeBtns}>
			    		<Board item={item.title} length={(item.title/parseFloat(maxEndLength))*(Dimensions.get('window').width-4)}/>
			    	</Swipeout>
	    		</View>
	    	</View>
	    );
	}

	render() {
		return (
		  	<View style={styles.container}>
			    <View style={styles.navContainer}>
			        <Text
			        	style={styles.navBack}
			          	onPress = { () => this.props.navigate('Screen3') }>Select boards
			        </Text>
			        <Text
			        	style={styles.navForward}
			          	onPress = { () => this.props.navigate('Screen5') }>Solution
			        </Text>
		        </View>
	    		<Instructions title="Please add ends by specifying their length and clicking 'Add'"/>
				<ListView dataSource={this.state.dataSource} renderRow={this.renderItem.bind(this)} style={styles.listview} enableEmptySections/>
				<AddSectionButton title="Add End" onPress={this.saveData} />
				<TextInput
					placeholder="Please enter length of end to add"
					style={{height: 40, borderColor: 'gray', borderWidth: 1, width: Dimensions.get('window').width}}
					onChangeText={this.saveLength}/>
		  	</View>
		);
	}
}